name: Close stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.TOKENBASE_BOT_GITHUB_SECRET }}
        stale-issue-message: 'This issue is stale because it has been open 21 days with no activity. Unless there is an update, it will be closed in 7 days.'
        stale-pr-message: 'This pull request is stale because it has been open 21 days with no activity. Unless there is an update, it will be closed in 7 days.'
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        days-before-stale: 21
        days-before-close: 7
